# Generated by Django 4.1.2 on 2023-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.CharField(default='anish', max_length=255),
        ),
    ]
