# Generated by Django 4.1.2 on 2023-04-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=255)),
                ('clientsproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.client')),
            ],
        ),
    ]
