# Generated by Django 4.1.2 on 2023-04-26 19:03

import django.contrib.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_client_id_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.CharField(default=django.contrib.auth.get_user, max_length=255),
        ),
    ]
