# Generated by Django 4.1.2 on 2023-04-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_client_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clientsproject',
        ),
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.project'),
            preserve_default=False,
        ),
    ]
