# Generated by Django 4.1.2 on 2023-04-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_remove_project_clientsproject_client_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='clientprojects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.client'),
            preserve_default=False,
        ),
    ]
